name: Hello world workflow
on: [push] # Triggers the workflow on every push to the repository

jobs:
  say-hello:
    runs-on: ubuntu-latest # Github hosted runners
    steps:
       - name: Greet the world
         run: "Hello, world!" # The command to execute
