name: feature-pipeline
on: workflow_dispatch # Triggers the workflow on every push to the repository
jobs:
  # Job name
  feature-pipeline:
    uses: suma-vadla18/workflows/.github/workflows/test.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'
    
  